### ISSUE TITLE
Can't produce OCaml documentation with MAKEOBJDIRPREFIX

### ISSUE THREAD

**Issue by koyfman** [michipili/bsdowl#211]
When using *MAKEOBJDIRPREFIX* `ocaml.manual.mk` fails to find previously generated `odoc` files. This works correctly with *MAKEOBJDIR* or when objects and sources live in the same directory.

**Comment by michipili** [comment]
Thanks to your feedback, I will take a look at this! :)

**Comment by koyfman** [comment]
Thanks!

**Comment by michipili** [comment]
Do you, by any chance, have some variables in *MAKEOBJDIRPREFIX* ?  These variables will *not* be expanded which means that **bsdmake** will fail to change to the corresponding object directory and can induce some puzzling behaviour.

The variable *MAKEOBJDIR* is expanded, so you could use it instead, together with *.CURDIR* or a modification of *.CURDIR*.

I experienced a similar issue while reworking the test suite a few days a go, after removing variables from *MAKEOBJDIRPREFIX* the problems vanished.

**Comment by koyfman** [comment]
That was it, thanks! :+1:
